version: '3'
services:
  nginx:
    build: ./web
    volumes:
    - "./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
    - "80:80"
    - "5984:5984"
    depends_on:
    - rabbitmq
    - couchdb
    links:
    - rabbitmq
    - couchdb
    - cluster
    restart: always
  rabbitmq:
    image: rabbitmq
    ports:
    - "35197:35197"
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    volumes:
    - "./config/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"
    - "./config/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins"
    restart: always
  couchdb:
    image: couchdb
    volumes:
    - "./data/couchdb/:/opt/couchdb/data"
    env_file: config/config.env
    restart: always
  cluster:
    build: ./service/cluster
    volumes:
    - "./service/cluster/:/app"
    env_file: config/config.env
    environment:
    - MIX_ENV=dev
    restart: always
    depends_on:
    - rabbitmq
    - couchdb
  auth:
    build: ./service/auth
    volumes:
    - "./service/auth/:/app"
    env_file: config/config.env
    environment:
    - MIX_ENV=dev
    restart: always
    depends_on:
    - couchdb
  status:
    build: ./service/status
    restart: always
  statistics:
    build: ./service/statistics
    restart: always
